# Generated by Django 4.0.5 on 2022-07-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('question1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('question3', models.CharField(max_length=50)),
            ],
        ),
    ]
