# Generated by Django 4.0.5 on 2022-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0002_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
