# Generated by Django 4.0.5 on 2022-07-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0005_remove_donate_date_created_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
