# Generated by Django 4.0.5 on 2022-07-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
