# Generated by Django 4.0.5 on 2022-07-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0008_donate_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='name',
            new_name='cardname',
        ),
        migrations.AlterField(
            model_name='donate',
            name='value',
            field=models.CharField(choices=[('25', "25€ --- Here's food, on me :)"), ('50', '50€ --- You helped me, so I am thankful'), ('100', '100€ --- I love animals!'), ('200', '200€ --- I just want a better world!'), ('350', '350€ --- We need to do something, animals deserve it as much as we do!!!')], default='25', max_length=10),
        ),
    ]
