# Generated by Django 4.0.5 on 2022-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0012_alter_donate_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pergunta1', models.CharField(max_length=50)),
                ('pergunta2', models.CharField(max_length=100)),
                ('pergunta3', models.IntegerField(default=0)),
                ('pergunta4', models.IntegerField(default=0)),
                ('pergunta5', models.CharField(max_length=50)),
            ],
        ),
    ]
