# Generated by Django 4.0.5 on 2022-07-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0013_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quizz',
        ),
    ]
