# Generated by Django 4.0.5 on 2022-07-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0014_delete_quizz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='nome',
            new_name='nomesddad',
        ),
    ]
