# Generated by Django 4.0.5 on 2022-07-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0015_rename_nome_quiz_nomesddad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='nomesddad',
            new_name='nomes',
        ),
    ]
