# Generated by Django 4.0.5 on 2022-07-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0017_rename_nomes_quiz_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
