# Generated by Django 4.0.5 on 2022-07-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0018_delete_blog_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
