# Generated by Django 4.0.5 on 2022-07-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0019_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pergunta3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pergunta4',
            field=models.CharField(max_length=10),
        ),
    ]
