# Generated by Django 4.0.5 on 2022-07-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0025_remove_customer_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpwild.customer'),
        ),
    ]
