# Generated by Django 4.0.5 on 2022-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0026_donate_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='donation',
            field=models.ManyToManyField(to='helpwild.donate'),
        ),
    ]
