# Generated by Django 4.0.5 on 2022-07-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpwild', '0028_remove_customer_donation_alter_donate_cardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='cardname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
